version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:11.1.0
    working_directory: ~/website
    steps:
      - checkout
      - run: git config --global user.email "krzystof.zuraw@fastmail.com" && git config --global user.name "Krzysztof Żuraw"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy
